### ISSUE TITLE
Pyrometallurgy

### ISSUE THREAD

**Issue by tomasbrod** [GregTechCEu/gregicality#481]
Pull request  #460 removed a set of blast furnance recipes (known in days of GT5U as pyrometallurgy iirc). I did not see this removal in changelogs. Was the recipeset removed in error? Or a means to fix the balance broken by x4, x8 ore-to-dust ration introduced in GTCE?
Thank you, and cc @ArchitektRadim

**Comment by DStrand1** [comment]
We removed it due to a poor chemical balance present in the recipes, and because recipes frequently conflicted in the EBF due to their inclusion. In total, we maybe only had about 10 maximum recipes like this. If there is significant desire to see them return (probably in a modified state), then we can add them back

**Comment by tomasbrod** [comment]
Thanks. I started working on balancing and re-adding those recipes with crafttweaker.

**Comment by tomasbrod** [comment]
Attaching my wip script: [gtpyrometallurgy.zs.txt](https://github.com/Gregicality/gregicality/files/6526302/gtpyrometallurgy.zs.txt)

**Comment by DStrand1** [comment]
Closing as resolved by GTCEu
